import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  test: {
    coverage: {
      include: [
        "src/app/api/search-token/route.ts",
        "src/app/api/coveo/conversation/route.ts",
        "src/lib/coveo/search-token.ts",
        "src/lib/coveo/ag-ui-stream.ts",
        "src/lib/coveo/search-agent-api.ts",
        "src/components/search/SearchSuggestions.tsx",
        "src/components/search/use-search-suggestions.ts",
        "src/components/content/TrendingContent.tsx",
        "src/components/commerce/ProductDiscoveryExperience.tsx",
        "src/components/layout/Header.tsx",
        "src/components/generative/GenerativeAnswer.tsx",
        "src/components/generative/GenerativeAnswerSkeleton.tsx",
        "src/components/generative/GenerativeAnswerContent.tsx",
        "src/components/generative/GenerativeCitations.tsx",
        "src/components/generative/GenerativeCitation.tsx",
        "src/components/generative/GenerativeFeedback.tsx",
        "src/components/generative/GenerativeError.tsx",
        "src/components/generative/GenerativeNoAnswer.tsx",
        "src/components/shared/ConfigurationNotice.tsx",
        "src/features/analytics/analytics.tsx",
        "src/features/commerce/headless/commerce-auth.ts",
        "src/features/commerce/headless/headless-commerce-mappers.ts",
        "src/features/commerce/models/commerce-models.ts",
        "src/features/feature-flags/env-feature-flags.ts",
        "src/features/feature-flags/feature-flags.ts",
        "src/features/generative/providers/coveo-generative-provider.ts",
        "src/features/generative/providers/feedback-provider.ts",
        "src/features/generative/providers/mock-generative-provider.ts",
        "src/features/conversation/providers/coveo-conversation-provider.ts",
        "src/features/conversation/providers/mock-conversation-provider.ts",
        "src/features/conversation/providers/conversation-errors.ts",
        "src/features/conversation/services/conversation-state.ts",
        "src/features/generative/services/citations.ts",
        "src/features/generative/services/generative-state.ts",
        "src/features/search/models/search-models.ts",
        "src/features/trending/providers/coveo-content-trending-provider.ts",
        "src/features/trending/providers/mock-trending-provider.ts",
        "src/features/trending/services/trending-urls.ts",
        "src/lib/coveo/content-search.ts",
        "src/lib/errors/application-error.ts",
        "src/lib/logging/logger.ts",
        "src/lib/runtime/runtime-config.ts",
      ],
      provider: "v8",
      reporter: ["text", "json-summary"],
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
    },
    environment: "jsdom",
    exclude: ["tests/e2e/**", "node_modules/**", "dist/**", ".next/**"],
    globals: false,
    restoreMocks: true,
  },
});
